services:
  - type: web
    name: asl-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: free
    envVars:
      - key: PORT
        value: 8501
